### ISSUE TITLE
YouTube Stats to Notion works... sometimes

### ISSUE THREAD

**Issue by rplmaxwell** [TomFrankly/pipedream-youtube-notion-sync#1]
In my testing with one or two YouTube video URLs, the Pipedream automation worked perfectly. However, when I imported more rows into the database, I got an error message 

Here's what Pipedream indicates:

`TypeError
Cannot read properties of undefined (reading 'url')`

Details:
`  at null.null (file:///tmp/__pdg__/dist/code/[xxxx]/component.mjs:360:49)
    at Array.map (null:null:null)
    at Object.buildUpdateArray (file:///tmp/__pdg__/dist/code/[xxxx]/component.mjs:349:37)
    at Object.run (file:///tmp/__pdg__/dist/code/[xxxx]/component.mjs:476:28)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at null.executeComponent (/var/task/launch_worker.js:229:22)
    at MessagePort.messageHandler (/var/task/launch_worker.js:726:28)`
    
Where `[xxxx]` represents a string of numbers and letters. Please let me know if I can provide any additional information. Thanks!

**Comment by TomFrankly** [comment]
Can you copy and paste the contents of the Log tab for this failed run?

**Comment by rplmaxwell** [comment]
There are so many lines here that I'm putting this into four google docs because I can't tell which parts are relevant for you. I shared them with your **secret email address** (starts with a "b" - you shared this with me at your VidCon talk).

<img width="961" alt="screenshot of logs" src="https://github.com/TomFrankly/pipedream-youtube-notion-sync/assets/128625754/6362f49a-b13f-498f-81d2-f518058dce9f">

1. https://docs.google.com/document/d/1R6VIiazSHLS-3d1b2tMIO5PUT-riDSNsnb9YF55bs94/edit?usp=sharing
2. https://docs.google.com/document/d/1HwFHoPmIgZEAUgCrRwp5CSnDjk6XZhqAiocrDTWyMeU/edit?usp=sharing
3. https://docs.google.com/document/d/1ncTm5Xnduj6P5UuryukXYN7oBIQlY2Aabob9NhuSKUY/edit?usp=sharing
4. https://docs.google.com/document/d/1-sFUFq2R2K5-9dJpUikoJWppzOPXycYuEMB2Z5DInDs/edit

If I can share anything else, please let me know. Thanks!

**Comment by rplmaxwell** [comment]
Hi Thomas - is there any additional information I can provide you with? Thanks!

**Comment by Shootda** [comment]
Hi Thomas, I have the exact same issue... is there anything I can provide to help figure this out?  Thanks.

**Comment by TomFrankly** [comment]
@Shootda if you can provide the error text and the text of the Log tab, that'd be great!

Unfortunately I'm in a very intense period of content work right now though, so I won't be able to dig into this until next week at least.

If anyone else would like to submit a PR, they're welcome to!

**Comment by Shootda** [comment]
@TomFrankly Here you go.  Please let me know if there is anything else you need. :) 

[10_23_2023 7_28_14 AM Rows from Notion_46 - Google Docs.pdf](https://github.com/TomFrankly/pipedream-youtube-notion-sync/files/13072129/10_23_2023.7_28_14.AM.Rows.from.Notion_46.-.Google.Docs.pdf)
![Screenshot 2023-10-23 072915](https://github.com/TomFrankly/pipedream-youtube-notion-sync/assets/86486728/5a63e169-40e8-4cf2-914d-489e1c8def40)

**Comment by TomFrankly** [comment]
@Shootda @rplmaxwell hey all - sorry this took so long, but I've finally fixed the issue that was causing the workflow to fail.

There are also a lot of other improvements. I'd recommend setting up a new copy of the workflow: https://go.thomasjfrank.com/pipedream-youtube-stats-notion-data/
