### ISSUE TITLE
It does NOT update the title!

### ISSUE THREAD

**Issue by edvinPL** [TomFrankly/pipedream-youtube-notion-sync#2]
Hello!

In here: https://community.thomasjfrank.com/c/tutorials/automation-sync-youtube-stats-to-notion this pipedream automation works… LIKE A DREAM!

It was already mentioned by Marius Dragan and Tracy Bell, though no solution was found.

Only shame is, it does NOT update the title! Considering search system is based on YOUTUBE link, it should not be (I HOPE!) that difficult for the system to UPDATE NAME (title) of the content piece located within All Content [UBCC].

Only issue is, my “scripting skill”=0.

**Comment by TomFrankly** [comment]
@edvinPL I left this out on purpose, as some people test title changes all the time and probably wouldn't want them updating in Notion. But it is actually pretty easy to implement.

Around line 400, there is this object:

```
const props = {
	[this.viewCount]: {
		number: row.views,
	},
	...(this.likeCount && {
		[this.likeCount]: {
			number: row.likes,
		},
	}),
	...(this.commentCount && {
		[this.commentCount]: {
			number: row.comments,
		},
	}),
	...(this.publishDate && {
		[this.publishDate]: {
			date: {
				start: row.publish,
			},
		},
	}),
};
```

Looking at the rest of the code, I believe all you'd need to do is update it to be this:

```
const props = {
	[this.videoTitle]: {
		title: [
			{
				text: {
					content: row.ytTitle,
				}
			}
		]
	},
	[this.viewCount]: {
		number: row.views,
	},
	...(this.likeCount && {
		[this.likeCount]: {
			number: row.likes,
		},
	}),
	...(this.commentCount && {
		[this.commentCount]: {
			number: row.comments,
		},
	}),
	...(this.publishDate && {
		[this.publishDate]: {
			date: {
				start: row.publish,
			},
		},
	}),
};
```

All I'm adding is the title block:

```
[this.videoTitle]: {
		title: [
			{
				text: {
					content: row.ytTitle,
				}
			}
		]
	},
```

I don't currently have time to add this to the workflow, but you should be able to copy and paste my code into a Code step in Pipedream, then make that change: https://github.com/TomFrankly/pipedream-youtube-notion-sync/blob/main/Youtube-Sync.js

Hope that helps!

**Comment by TomFrankly** [comment]
Hey @edvinPL – I got around to adding this feature!

You'll probably have the easiest time just setting up a new copy of the workflow: https://go.thomasjfrank.com/pipedream-youtube-stats-notion-data/

It should also be a lot faster now.
